using System.Collections.Generic;

namespace SportsbookAggregation.SportsBooks.Mappers
{
    public static class MascotMapper
    {
        public static string GetFullNameUsingCollege(string collegeName)
        {
            if (locationToMascotDictionary.TryGetValue(collegeName, out string mascot))
                return collegeName + " " + mascot;
            return collegeName;
        }

        private static Dictionary<string, string> locationToMascotDictionary = new Dictionary<string, string>
        {
            { "Air Force", "Falcons" },
            { "Akron", "Zips" },
            { "Alabama", "Crimson Tide" },
            { "Appalachian State", "Mountaineers" },
            { "Arizona", "Wildcats" },
            { "Arizona State", "Sun Devils" },
            { "Arkansas", "Razorbacks" },
            { "Arkansas State", "Red Wolves" },
            { "Army", "Black Knights" },
            { "Auburn", "Tigers" },
            { "Ball State", "Cardinals" },
            { "Baylor", "Bears" },
            { "Boise State", "Broncos" },
            { "Boston College", "Eagles" },
            { "Bowling Green", "Falcons" },
            { "Buffalo", "Bulls" },
            { "BYU", "Cougars" },
            { "California", "Golden Bears" },
            { "Central Michigan", "Chippewas" },
            { "Charlotte", "49ers" },
            { "Cincinnati", "Bearcats" },
            { "Clemson", "Tigers" },
            { "Coastal Carolina", "Chanticleers" },
            { "Colorado", "Buffaloes" },
            { "Colorado State", "Rams" },
            { "Duke", "Blue Devils" },
            { "East Carolina", "Pirates" },
            { "Eastern Michigan", "Eagles" },
            { "FIU", "Panthers" },
            { "Florida", "Gators" },
            { "Florida Atlantic", "Owls" },
            { "Florida State", "Seminoles" },
            { "Fresno State", "Bulldogs" },
            { "Georgia", "Bulldogs" },
            { "Georgia Southern", "Eagles" },
            { "Georgia State", "Panthers" },
            { "Georgia Tech", "Yellow Jackets" },
            { "Hawaii", "Rainbow Warriors" },
            { "Houston", "Cougars" },
            { "Illinois", "Fighting Illini" },
            { "Indiana", "Hoosiers" },
            { "Iowa", "Hawkeyes" },
            { "Iowa State", "Cyclones" },
            { "Kansas", "Jayhawks" },
            { "Kansas State", "Wildcats" },
            { "Kent State", "Golden Flashes" },
            { "Kentucky", "Wildcats" },
            { "Liberty", "Flames" },
            { "Louisiana", "Ragin' Cajuns" },
            { "Louisiana-Monroe", "Warhawks" },
            { "Louisiana Tech", "Bulldogs" },
            { "Louisville", "Cardinals" },
            { "LSU", "Tigers" },
            { "Merrimack", "Warriors" },
            { "Marshall", "Thundering Herd" },
            { "Maryland", "Terrapins" },
            { "Memphis", "Tigers" },
            { "Miami (FL)", "Hurricanes" },
            { "Miami (OH)", "RedHawks" },
            { "Michigan", "Wolverines" },
            { "Michigan State", "Spartans" },
            { "Middle Tennessee", "Blue Raiders" },
            { "Minnesota", "Golden Gophers" },
            { "Mississippi State", "Bulldogs" },
            { "Missouri", "Tigers" },
            { "Navy", "Midshipmen" },
            { "NC State", "Wolfpack" },
            { "Nebraska", "Cornhuskers" },
            { "Nevada", "Wolf Pack" },
            { "New Mexico", "Lobos" },
            { "New Mexico State", "Aggies" },
            { "North Carolina", "Tar Heels" },
            { "North Texas", "Mean Green" },
            { "Northern Illinois", "Huskies" },
            { "Northwestern", "Wildcats" },
            { "Notre Dame", "Fighting Irish" },
            { "Ohio", "Bobcats" },
            { "Ohio State", "Buckeyes" },
            { "Oklahoma", "Sooners" },
            { "Oklahoma State", "Cowboys" },
            { "Old Dominion", "Monarchs" },
            { "Ole Miss", "Rebels" },
            { "Oregon", "Ducks" },
            { "Oregon State", "Beavers" },
            { "Penn State", "Nittany Lions" },
            { "Pittsburgh", "Panthers" },
            { "Purdue", "Boilermakers" },
            { "Rice", "Owls" },
            { "Rutgers", "Scarlet Knights" },
            { "San Diego State", "Aztecs" },
            { "San Jose State", "Spartans" },
            { "SMU", "Mustangs" },
            { "South Alabama", "Jaguars" },
            { "South Carolina", "Gamecocks" },
            { "South Florida", "Bulls" },
            { "Southern Miss", "Golden Eagles" },
            { "Stanford", "Cardinal" },
            { "Syracuse", "Orange" },
            { "TCU", "Horned Frogs" },
            { "Temple", "Owls" },
            { "Tennessee", "Volunteers" },
            { "Texas", "Longhorns" },
            { "Texas A&M", "Aggies" },
            { "Texas State", "Bobcats" },
            { "Texas Tech", "Red Raiders" },
            { "Toledo", "Rockets" },
            { "Troy", "Trojans" },
            { "Tulane", "Green Wave" },
            { "Tulsa", "Golden Hurricane" },
            { "UAB", "Blazers" },
            { "UCF", "Knights" },
            { "UCLA", "Bruins" },
            { "UConn", "Huskies" },
            { "UMass", "Minutemen" },
            { "UNLV", "Rebels" },
            { "USC", "Trojans" },
            { "UTEP", "Miners" },
            { "UTSA", "Roadrunners" },
            { "Utah", "Utes" },
            { "Utah State", "Aggies" },
            { "Vanderbilt", "Commodores" },
            { "Virginia", "Cavaliers" },
            { "Virginia Tech", "Hokies" },
            { "Wake Forest", "Demon Deacons" },
            { "Washington", "Huskies" },
            { "Washington State", "Cougars" },
            { "West Virginia", "Mountaineers" },
            { "Western Kentucky", "Hilltoppers" },
            { "Western Michigan", "Broncos" },
            { "Wisconsin", "Badgers" },
            { "Wyoming", "Cowboys" },
            { "Adams State University", "Grizzlies" },
            { "Albany State University", "Golden Rams" },
            { "Alderson Broaddus University", "Battlers" },
            { "Allen University", "Yellow Jackets" },
            { "American International College", "Yellow Jackets" },
            { "Angelo State University", "Rams" },
            { "Arkansas Tech University", "Wonder Boys" },
            { "University of Arkansas at Monticello", "Boll Weevils" },
            { "Ashland University", "Eagles" },
            { "Assumption University", "Greyhounds" },
            { "Augustana University", "Vikings" },
            { "Azusa Pacific University", "Cougars" },
            { "Barton College", "Bulldogs" },
            { "Bemidji State University", "Beavers" },
            { "Benedict College", "Tigers" },
            { "Bentley University", "Falcons" },
            { "Black Hills State University", "Yellow Jackets" },
            { "Bloomsburg University of Pennsylvania", "Huskies" },
            { "Bowie State University", "Bulldogs" },
            { "California University of Pennsylvania", "Vulcans" },
            { "Carson–Newman University", "Eagles" },
            { "Catawba College", "Indians" },
            { "University of Central Missouri", "Mules" },
            { "University of Central Oklahoma", "Bronchos" },
            { "Central State University", "Marauders" },
            { "Central Washington University", "Wildcats" },
            { "Chadron State College", "Eagles" },
            { "University of Charleston", "Golden Eagles" },
            { "Chowan University", "Hawks" },
            { "Clarion University of Pennsylvania", "Golden Eagles" },
            { "Clark Atlanta University", "Panthers" },
            { "Colorado Mesa University", "Mavericks" },
            { "Colorado School of Mines", "Orediggers" },
            { "Colorado State University–Pueblo", "ThunderWolves" },
            { "Concord University", "Mountain Lions" },
            { "Concordia University–St. Paul", "Golden Bears" },
            { "Davenport University", "Panthers" },
            { "Delta State University", "Statesmen" },
            { "East Central University", "Tigers" },
            { "East Stroudsburg University of Pennsylvania", "Warriors" },
            { "Eastern New Mexico University", "Greyhounds" },
            { "Edinboro University of Pennsylvania", "Fighting Scots" },
            { "Elizabeth City State University", "Vikings" },
            { "Emporia State University", "Hornets" },
            { "Erskine College", "Flying Fleet" },
            { "Fairmont State University", "Falcons" },
            { "Fayetteville State University", "Broncos" },
            { "Ferris State University", "Bulldogs" },
            { "University of Findlay", "Oilers" },
            { "Fort Hays State University", "Tigers" },
            { "Fort Lewis College", "Skyhawks" },
            { "Fort Valley State University", "Wildcats" },
            { "Franklin Pierce University", "Ravens" },
            { "Frostburg State University", "Bobcats" },
            { "Gannon University", "Golden Knights" },
            { "Glenville State College", "Pioneers" },
            { "Grand Valley State University", "Lakers" },
            { "Harding University", "Bisons" },
            { "Henderson State University", "Reddies" },
            { "Hillsdale College", "Chargers" },
            { "Indiana University of Pennsylvania", "Crimson Hawks" },
            { "University of Indianapolis", "Greyhounds" },
            { "Johnson C. Smith University", "Golden Bulls" },
            { "Kentucky State University", "Thorobreds" },
            { "Kentucky Wesleyan College", "Panthers" },
            { "Kutztown University of Pennsylvania", "Golden Bears" },
            { "Lake Erie College", "Storm" },
            { "Lane College", "Dragons" },
            { "Lenoir–Rhyne University", "Bears" },
            { "Limestone University", "Saints" },
            { "Lincoln University (MO)", "Blue Tigers" },
            { "Lincoln University (PA)", "Lions" },
            { "Lindenwood University", "Lions" },
            { "Livingstone College", "Blue Bears" },
            { "Lock Haven University of Pennsylvania", "Bald Eagles" },
            { "Mars Hill University", "Lions" },
            { "University of Mary", "Marauders" },
            { "McKendree University", "Bearcats" },
            { "Mercyhurst University", "Lakers" },
            { "Michigan Technological University", "Huskies" },
            { "Midwestern State University", "Mustangs" },
            { "Miles College", "Golden Bears" },
            { "Millersville University of Pennsylvania", "Marauders" },
            { "Minnesota State University, Mankato", "Mavericks" },
            { "Minnesota State University Moorhead", "Dragons" },
            { "University of Minnesota Duluth", "Bulldogs" },
            { "Minot State University", "Beavers" },
            { "Mississippi College", "Choctaws" },
            { "Missouri University of Science and Technology", "Miners" },
            { "Missouri Southern State University", "Lions" },
            { "Missouri Western State University", "Griffons" },
            { "Morehouse College", "Maroon Tigers" },
            { "University of Nebraska at Kearney", "Lopers" },
            { "University of New Haven", "Chargers" },
            { "New Mexico Highlands University", "Cowboys" },
            { "Newberry College", "Wolves" },
            { "University of North Carolina at Pembroke", "Braves" },
            { "North Greenville University", "Crusaders" },
            { "Northeastern State University", "RiverHawks" },
            { "Northern Michigan University", "Wildcats" },
            { "Northern State University", "Wolves" },
            { "Northwest Missouri State University", "Bearcats" },
            { "Northwestern Oklahoma State University", "Rangers" },
            { "Northwood University", "Timberwolves" },
            { "Notre Dame College", "Falcons" },
            { "Ohio Dominican University", "Panthers" },
            { "Oklahoma Baptist University", "Bison" },
            { "Ouachita Baptist University", "Tigers" },
            { "Pace University", "Setters" },
            { "Pittsburg State University", "Gorillas" },
            { "Quincy University", "Hawks" },
            { "Saginaw Valley State University", "Cardinals" },
            { "Saint Anselm College", "Hawks" },
            { "Saint Augustine's University", "Falcons" },
            { "Savannah State University", "Tigers" },
            { "Seton Hill University", "Griffins" },
            { "Shaw University", "Bears" },
            { "Shepherd University", "Rams" },
            { "Shippensburg University of Pennsylvania", "Red Raiders" },
            { "Shorter University", "Hawks" },
            { "Simon Fraser University", "Clan" },
            { "University of Sioux Falls", "Cougars" },
            { "Slippery Rock University of Pennsylvania", "The Rock" },
            { "South Dakota School of Mines and Technology", "Hardrockers" },
            { "Southeastern Oklahoma State University", "Savage Storm" },
            { "Southern Arkansas University", "Muleriders" },
            { "Southern Connecticut State University", "Fighting Owls" },
            { "Southern Nazarene University", "Crimson Storm" },
            { "Southwest Baptist University", "Bearcats" },
            { "Southwest Minnesota State University", "Mustangs" },
            { "Southwestern Oklahoma State University", "Bulldogs" },
            { "Stonehill College", "Skyhawks" },
            { "Texas A&M University–Commerce", "Lions" },
            { "Texas A&M University–Kingsville", "Javelinas" },
            { "University of Texas of the Permian Basin", "Falcons" },
            { "Tiffin University", "Dragons" },
            { "Truman State University", "Bulldogs" },
            { "Tusculum University", "Pioneers" },
            { "Tuskegee University", "Golden Tigers" },
            { "Upper Iowa University", "Peacocks" },
            { "Valdosta State University", "Blazers" },
            { "Virginia State University", "Trojans" },
            { "Virginia Union University", "Panthers" },
            { "University of Virginia's College at Wise", "Cavaliers" },
            { "Walsh University", "Cavaliers" },
            { "Washburn University", "Ichabods" },
            { "Wayne State University", "Warriors" },
            { "Wayne State College", "Wildcats" },
            { "University of West Alabama", "Tigers" },
            { "West Chester University", "Golden Rams" },
            { "University of West Florida", "Argonauts" },
            { "University of West Georgia", "Wolves" },
            { "West Liberty University", "Hilltoppers" },
            { "West Texas A&M University", "Buffaloes" },
            { "West Virginia State University", "Yellow Jackets" },
            { "West Virginia Wesleyan College", "Bobcats" },
            { "Western Colorado University", "Mountaineers" },
            { "Western New Mexico University", "Mustangs" },
            { "Western Oregon University", "Wolves" },
            { "Wheeling University", "Cardinals" },
            { "William Jewell College", "Cardinals" },
            { "Wingate University", "Bulldogs" },
            { "Winona State University", "Warriors" },
            { "Winston–Salem State University", "Rams" },
            { "Abilene Christian", "Wildcats" },
            { "Alabama A&M", "Bulldogs" },
            { "Alabama State", "Hornets" },
            { "Albany", "Great Danes" },
            { "Alcorn State", "Braves" },
            { "Arkansas-Pine Bluff", "Golden Lions" },
            { "Austin Peay", "Governors" },
            { "Bethune-Cookman", "Wildcats" },
            { "Brown", "Bears" },
            { "Bryant", "Bulldogs" },
            { "Bucknell", "Bison" },
            { "Butler", "Bulldogs" },
            { "Cal Poly", "Mustangs" },
            { "Campbell", "Fighting Camels" },
            { "Central Arkansas", "Bears" },
            { "Central Connecticut", "Blue Devils" },
            { "Charleston Southern", "Buccaneers" },
            { "Chattanooga", "Mocs" },
            { "The Citadel", "Bulldogs" },
            { "Colgate", "Raiders" },
            { "Columbia", "Lions" },
            { "Cornell", "Big Red" },
            { "Dartmouth", "Big Green" },
            { "Davidson", "Wildcats" },
            { "Dayton", "Flyers" },
            { "Delaware", "Fightin' Blue Hens" },
            { "Delaware State", "Hornets" },
            { "Drake", "Bulldogs" },
            { "Duquesne", "Dukes" },
            { "East Tennessee State", "Buccaneers" },
            { "Eastern Illinois", "Panthers" },
            { "Eastern Kentucky", "Colonels" },
            { "Eastern Washington", "Eagles" },
            { "Elon", "Phoenix" },
            { "Florida A&M", "Rattlers" },
            { "Fordham", "Rams" },
            { "Furman", "Paladins" },
            { "Gardner-Webb", "Runnin' Bulldogs" },
            { "Georgetown", "Hoyas" },
            { "Grambling State", "Tigers" },
            { "Hampton", "Pirates" },
            { "Harvard", "Crimson" },
            { "Holy Cross", "Crusaders" },
            { "Houston Baptist", "Huskies" },
            { "Howard", "Bison" },
            { "Idaho", "Vandals" },
            { "Idaho State", "Bengals" },
            { "Illinois State", "Redbirds" },
            { "Incarnate Word", "Cardinals" },
            { "Indiana State", "Sycamores" },
            { "Jackson State", "Tigers" },
            { "Jacksonville State", "Gamecocks" },
            { "James Madison", "Dukes" },
            { "Kennesaw State", "Owls" },
            { "Lafayette", "Leopards" },
            { "Lamar", "Cardinals" },
            { "Lehigh", "Mountain Hawks" },
            { "LIU[d]", "Sharks" },
            { "Maine", "Black Bears" },
            { "Marist", "Red Foxes" },
            { "McNeese State", "Cowboys" },
            { "Mercer", "Bears" },
            { "Mississippi Valley State", "Delta Devils" },
            { "Missouri State", "Bears" },
            { "Monmouth", "Hawks" },
            { "Montana", "Grizzlies" },
            { "Montana State", "Bobcats" },
            { "Morehead State", "Eagles" },
            { "Morgan State", "Bears" },
            { "Murray State", "Racers" },
            { "New Hampshire", "Wildcats" },
            { "Nicholls", "Colonels" },
            { "Norfolk State", "Spartans" },
            { "North Carolina A&T", "Aggies" },
            { "North Carolina Central", "Eagles" },
            { "North Dakota", "Fighting Hawks" },
            { "North Dakota State", "Bison" },
            { "Northern Arizona", "Lumberjacks" },
            { "Northern Colorado", "Bears" },
            { "Northern Iowa", "Panthers" },
            { "Northwestern State", "Demons" },
            { "Penn", "Quakers" },
            { "Portland State", "Vikings" },
            { "Prairie View A&M", "Panthers" },
            { "Presbyterian", "Blue Hose" },
            { "Princeton", "Tigers" },
            { "Rhode Island", "Rams" },
            { "Richmond", "Spiders" },
            { "Robert Morris", "Colonials" },
            { "Sacramento State", "Hornets" },
            { "Sacred Heart", "Pioneers" },
            { "Saint Francis", "Red Flash" },
            { "Sam Houston State", "Bearkats" },
            { "Samford", "Bulldogs" },
            { "San Diego", "Toreros" },
            { "South Carolina State", "Bulldogs" },
            { "South Dakota", "Coyotes" },
            { "South Dakota State", "Jackrabbits" },
            { "Southeast Missouri State", "Redhawks" },
            { "Southeastern Louisiana", "Lions" },
            { "Southern", "Jaguars" },
            { "Southern Illinois", "Salukis" },
            { "Southern Utah", "Thunderbirds" },
            { "Stephen F. Austin", "Lumberjacks" },
            { "Stetson", "Hatters" },
            { "Stony Brook", "Seawolves" },
            { "Tennessee State", "Tigers" },
            { "Tennessee Tech", "Golden Eagles" },
            { "Texas Southern", "Tigers" },
            { "Towson", "Tigers" },
            { "UC Davis", "Aggies" },
            { "UT Martin", "Skyhawks" },
            { "Valparaiso", "Crusaders" },
            { "Villanova", "Wildcats" },
            { "VMI", "Keydets" },
            { "Wagner", "Seahawks" },
            { "Weber State", "Wildcats" },
            { "Western Carolina", "Catamounts" },
            { "Western Illinois", "Leathernecks" },
            { "William & Mary", "Tribe" },
            { "Wofford", "Terriers" },
            { "Yale", "Bulldogs" },
            { "Youngstown State", "Penguins" },
            { "American", "Eagles" },
            { "Bellarmine", "Knights" },
            { "Belmont", "Bruins" },
            { "Binghamton", "Bearcats" },
            { "Boston University", "Terriers" },
            { "Bradley", "Braves" },
            { "Cal State Bakersfield", "Roadrunners" },
            { "Cal State Fullerton", "Titans" },
            { "Cal State Northridge", "Matadors" },
            { "California Baptist", "Lancers" },
            { "Canisius", "Golden Griffins" },
            { "Charleston", "Cougars" },
            { "Chicago State", "Cougars" },
            { "Cleveland State", "Vikings" },
            { "Creighton", "Bluejays" },
            { "Denver", "Pioneers" },
            { "DePaul", "Blue Demons" },
            { "Detroit Mercy", "Titans" },
            { "Drexel", "Dragons" },
            { "Evansville", "Purple Aces" },
            { "Fairfield", "Stags" },
            { "Fairleigh Dickinson", "Knights" },
            { "Florida Gulf Coast", "Eagles" },
            { "George Mason", "Patriots" },
            { "George Washington", "Colonials" },
            { "Gonzaga", "Bulldogs/Zags" },
            { "Grand Canyon", "Antelopes" },
            { "Green Bay", "Phoenix" },
            { "Hartford", "Hawks" },
            { "High Point", "Panthers" },
            { "Hofstra", "Pride" },
            { "IUPUI", "Jaguars" },
            { "Iona", "Gaels" },
            { "Jacksonville", "Dolphins" },
            { "Kansas City", "Roos" },
            { "La Salle", "Explorers" },
            { "Lipscomb", "Bisons" },
            { "Little Rock", "Trojans" },
            { "Long Beach State", "The Beach" },
            { "Longwood", "Lancers" },
            { "Loyola Chicago", "Ramblers" },
            { "Loyola Maryland", "Greyhounds" },
            { "Loyola Marymount", "Lions" },
            { "Manhattan", "Jaspers" },
            { "Marquette", "Golden Eagles" },
            { "Maryland Eastern Shore", "Hawks" },
            { "Milwaukee", "Panthers" },
            { "Mount Saint Mary's", "Mountaineers" },
            { "New Orleans", "Privateers" },
            { "Niagara", "Purple Eagles" },
            { "NJIT", "Highlanders" },
            { "North Florida", "Ospreys" },
            { "Northeastern", "Huskies" },
            { "Northern Kentucky", "Norse" },
            { "Oakland", "Golden Grizzlies" },
            { "Omaha", "Mavericks" },
            { "Oral Roberts", "Golden Eagles" },
            { "Pacific", "Tigers" },
            { "Pepperdine", "Waves" },
            { "Portland", "Pilots" },
            { "Providence", "Friars" },
            { "Purdue Fort Wayne", "Mastodons" },
            { "Quinnipiac", "Bobcats" },
            { "Radford", "Highlanders" },
            { "Rider", "Broncs" },
            { "St. Bonaventure", "Bonnies" },
            { "St. Francis Brooklyn", "Terriers" },
            { "St. John's", "Red Storm" },
            { "Saint Joseph's", "Hawks" },
            { "Saint Louis", "Billikens" },
            { "Saint Mary's", "Gaels" },
            { "Saint Peter's", "Peacocks and Peahens" },
            { "San Francisco", "Dons" },
            { "Santa Clara", "Broncos" },
            { "SU", "Redhawks" },
            { "Seton Hall", "Pirates" },
            { "Siena", "Saints" },
            { "SIU Edwardsville", "Cougars" },
            { "South Carolina Upstate", "Spartans" },
            { "Texas A&M–Corpus Christi", "Islanders" },
            { "Texas–Arlington", "Mavericks" },
            { "UC Riverside", "Highlanders" },
            { "UC Irvine", "Anteaters" },
            { "UC San Diego", "Tritons" },
            { "UC Santa Barbara", "Gauchos" },
            { "UIC", "Flames" },
            { "UMass Lowell", "River Hawks" },
            { "UMBC", "Retrievers" },
            { "UNC Asheville", "Bulldogs" },
            { "UNC Greensboro", "Spartans" },
            { "UNC Wilmington", "Seahawks" },
            { "Utah Valley", "Wolverines" },
            { "UTRGV", "Vaqueros" },
            { "Vermont", "Catamounts" },
            { "VCU", "Rams" },
            { "Wichita State", "Shockers" },
            { "Winthrop", "Eagles" },
            { "Wright State", "Raiders" },
            { "Xavier", "Musketeers" },
            { "UNA", "Lions" },
            { "Coppin State", "Eagles" },
            { "UMKC", "Kangaroos" },
            { "Dixie State", "Trailblazers" },
            { "Tarleton State", "Texans" }
        };
    }
}
